plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - lib/apollo-studio-tracing/proto/apollo_pb.rb

#
# We prefer trailing commas so that the git diff is reduced when adding elements
#
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
Layout/LineLength:
  Max: 100

Naming/FileName:
  Exclude:
    - 'lib/apollo-studio-tracing.rb'

# Development dependencies live in the gemspec, not the Gemfile.
Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
